### ISSUE TITLE
Zonnepanelen data

### ISSUE THREAD

**Issue by bboerendans** [homewizard/python-homewizard-energy#318]
Dag,

Wij hebben energy+ aangeschaft, en zien daardoor de opbrengst van de zonnepanelen netjes in de app. Is het op een of andere manier mogelijk data deze data ook in Home Assistant terecht kan komen? Gezien de growatt integratie met HA zelf merendeel van de tijd niet werkt ivm blockings van Growatt kant.

Een andere vraag is, ik zie in HA geen data bij de Total energy export. En dit zou mooi zijn voor het Energie dashboard in HA. Als ik de data in de local api bekijk, is er wel data:

  "total_power_export_kwh": 2472.309,
  "total_power_export_t1_kwh": 821.438,
  "total_power_export_t2_kwh": 1650.871,

**Comment by DCSBL** [comment]
Hey! Eigenlijk is deze plek bedoeld voor problemen of discussies rondom deze Python library. Dat dit project gebruikt wordt voor Home Assistant is een bijzaak. Dit soort vragen kan je het beste stellen op het forum, zie http://home-assistant.io/help/.

Maar nu je hier toch bent... 🙂 

> ... Is het op een of andere manier mogelijk data deze data ook in Home Assistant terecht kan komen? ...

Nee, het uitlezen van de omvormer is een verbinding vanuit de HomeWizard cloud naar de omvormers. De Home Assistant integratie leest alleen apparaten direct uit en kan niet communiceren met de cloud omdat alles lokaal werkt. Normaal adviseer ik je om de Growatt integratie van Home Assistant te gebruiken, maar vanwege de instabiliteit snap ik je vraag. Het beste advies dat ik je kan geven is een onafhankelijke kWh meter tussen de omvormer en je aansluiting plaatsen, zoals de HomeWizard kWh Meter.

> ... ik zie in HA geen data bij de Total energy export. ...

Dat zou gewoon moeten werken, mogelijk zijn de sensoren nog uitgeschakeld binnen Home Assistant. Kijk even of ze in de lijst staan van 'Entity not shown' en schakel ze daar in. Als je hier nog steeds problemen mee hebt dan kan je het best, zoals al aangegeven, een issue openen bij Home Assistant ([link](https://github.com/home-assistant/core/issues/new/choose))

<img width="324" alt="image" src="https://github.com/homewizard/python-homewizard-energy/assets/74970928/33a7076e-f88b-4fc3-8ed5-9990c7c942ea">
