### ISSUE TITLE
L/pm calculations

### ISSUE THREAD

**Issue by baudneo** [homewizard/python-homewizard-energy#407]
I don't use this repo but, a user on the Hass forum does and is having an issue with the L/pm sensor from the water meter reader.

They are saying that when there are 0 pulses per minute, the lpm sensor is sending erroneous data of 0 or 1.27 L/pm, this plays havoc on Hass automations that are time based; if lpm <= 0 for x minutes, automations never fire due to the sensor bouncing between 0 and 1.27 even when no water is flowing. See [this Hass forum post](https://community.home-assistant.io/t/how-to-average-oscillating-sensor-readings-due-to-sensor-resolution/768276/10).

Can you point me towards where in the code the lpm calculations are performed?

Also, it would be beneficial to expose the pulse counter for users who want tighter control over their stats.

TIA and thanks for your work!

**Comment by DCSBL** [comment]
Hi!

The calculation is handled in the device firmware so the code to that is not available. This is the first time we've encountered this issue. It might be worth directing the user to HomeWizard Support to check if the device is faulty.

This library serves as a bridge between the device and its implementation (typically Home Assistant). Any filtering should be handled within the implementation.

We can investigate if we have to add some filtering in Home Assistant, but we'll need to collect more cases to assess how many users are affected.

**Comment by baudneo** [comment]
Awesome, thanks. I'll forward this info and advise the user to reach out to support for further troubleshooting.

**Comment by baudneo** [comment]
I'll close the issue as I'm out of the loop. Hopefully the user reaches out! Thanks!
